name: Test Secret

on:
  workflow_dispatch:  # Permite ejecutarlo manualmente desde la pestaña "Actions"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check if DOCKERHUB_TOKEN is loaded
        run: |
          if [ -z "${{ secrets.DOCKERHUB_TOKEN }}" ]; then
            echo "❌ DOCKERHUB_TOKEN is not set"
            exit 1
          else
            echo "✅ DOCKERHUB_TOKEN is set"
          fi
